### ISSUE TITLE
concatenate the cert and key?

### ISSUE THREAD

**Issue by killbus** [humenius/traefik-certs-dumper#13]
some stuffs like haproxy need certificate contains both the **public certificate** and **private key**, maybe we need a chain.pem like this?

`cat cert.pem key.pem > domain.pem`

**Comment by humenius** [comment]
Should be possible, however for now I don't know what might be the best way to implement this feature. Something that came up in my mind was to add a "switch" which toggle between appending both public and private key into a single file. This approach is okay until someone wishes a "mixed" mode, allowing users to selectively append a domain's public and private key to a single file. If we really need to implement a mixed mode, I hope that extending command argument parsing in Bash won't be a hassle.
 
 
some stuffs like haproxy need certificate contains both the public certificate and private key, maybe we need a chain.pem like this?
cat cert.pem key.pem > fullchain.pem

**Comment by pwatk** [comment]
PKCS#12 support would be good too.

**Comment by humenius** [comment]
> PKCS#12 support would be good too.

This does require `openssl`, doesn't it?

**Comment by pwatk** [comment]
Yes. I can't remember what I wanted this for but I'm sure others might find it useful.

**Comment by othiman** [comment]
Hi. I tried to create a pull request since I needed this feature for myself. For me it is working that way.
