### ISSUE TITLE
why the need for env "DOMAIN"

### ISSUE THREAD

**Issue by motey** [humenius/traefik-certs-dumper#15]
Hi, first off thanks for this handy, helpful tool :heart: 
i guess many people will use `traefik-certs-dumper`in context with some kind of container manager. `treafik2` in my case. and useally you find yourself creating a lot of containers (sometimes even dynamic) with many domains and subdomains
In such a case its a pain to manually curate the `DOMAIN` env for traefik-certs-dumper. But why do i need to?

When parsing the json file, `traefik-certs-dumper` should have all the informations in `acme.json` it needs, doesnt it? 

```json
....
"Certificates": [
      {
        "domain": {
          "main": "mydomain.com"
        },
        "certificate": "loooongcertstring"
        "key": "longkeystring"
        "Store": "default"
      },
      {
        "domain": {
          "main": "myotherdomain.com"
        },
        "certificate": "loooongothercertstring"
        "key": "longothereystring"
        "Store": "default"
      }
    ]
  }
....
```
Would be great if `DOMAIN` would be an optional value.
Do i ignore something or should that be technical possible?

cheers, motey

**Comment by humenius** [comment]
I think this is something that was a "left over" of [Mailu's cert dumper](https://github.com/Mailu/Mailu/tree/master/optional/traefik-certdumper).

In theory, you're right. I don't really know why I haven't noticed it before because I probably didn't really care too much about that. 😅 

In case the `traefik-certs-dumper` does not dump any other files than domain certificates, I guess this shouldn't be a big hassle to implement.

**Comment by humenius** [comment]
> I think this is something that was a "left over" of [Mailu's cert dumper](https://github.com/Mailu/Mailu/tree/master/optional/traefik-certdumper).

To clarify: No, it isn't a left over. It's meant to be there so you can selectively dump certificates.
I will add the possibility to dump the whole file if `DOMAIN` environment variable is not set.

**Comment by humenius** [comment]
Feature is implemented. I think I will create the release today as all associated issues are resolved (hopefully :))
