### ISSUE TITLE
Traefik_certdumper - mailcow FATAL ERROR

### ISSUE THREAD

**Issue by Ice-Cue** [humenius/traefik-certs-dumper#16]
Hello,

i am getting this error on my system. and my Mailserver, Mailcow, is not reciving an Certification. do you know the error?

traefik_certdumper   | traefik-certs-dumper bash script by Humenius <contact@humenius.me>
traefik_certdumper   | Usage: /run.sh [-r|--restart-containers <arg>] [-h|--help]
traefik_certdumper   |  -r, --restart-containers: Restart containers passed as comma-separated container names (no default)
traefik_certdumper   |  -h, --help: Prints help
traefik_certdumper   | Environment variables:
traefik_certdumper   |  DOMAIN: Domains whose certificates will be extracted

thx for your help :-)

**Comment by humenius** [comment]
Can you provide the version you were using and a snippet of your `docker-compose.yml` where you are using the image?

**Comment by Ice-Cue** [comment]
i fixed the problem by reconfiguring all :-) 
thx

**Comment by humenius** [comment]
On `certdumper.command`, you need to add another `-` between the `-` and `restart-containers`.
Also, make sure you're using the right service names for `--restart-containers`.

**Comment by Ice-Cue** [comment]
thx. now it works. you are the best :-)
