### ISSUE TITLE
Change of ownership not applied to all files

### ISSUE THREAD

**Issue by pwatk** [humenius/traefik-certs-dumper#9]
Below is my changes to run.sh to fix change of ownership only being applied to the first file it finds.

```
--- run.sh	2020-06-03 14:49:22.000000000 +0100
+++ new.run.sh	2020-06-13 22:02:46.075416100 +0100
@@ -73,7 +73,10 @@
       log "Combination ${OVERRIDE_UID}:${OVERRIDE_GID} is invalid. Skipping file ownership change..."
     else
       log "Changing ownership of certificates and keys"
-      find ${outputdir}/ -type f -name "*.pem" -print0 | xargs chown "${OVERRIDE_UID}":"${OVERRIDE_GID}"
+      #find ${outputdir}/ -type f -name "*.pem" -print0 | xargs chown "${OVERRIDE_UID}":"${OVERRIDE_GID}"
+      find ${outputdir}/ -type f -name "*.pem" | while read f ;do 
+        chown "${OVERRIDE_UID}":"${OVERRIDE_GID}" "$f"
+      done
     fi
   fi
 

```

**Comment by humenius** [comment]
Thank you for your suggestion. I'll try to take a look at it ASAP.

**Comment by pwatk** [comment]
Thank you.

My I also suggest adding  `chmod g+r "$f" ` after the chown line so keys.pem gives read privileges to the new GID.

**Comment by humenius** [comment]
> 
> 
> Thank you.
> 
> My I also suggest adding `chmod g+r "$f" ` after the chown line so keys.pem gives read privileges to the new GID.

Don't they carry over after `chown`?

**Comment by pwatk** [comment]
The certificate can be read by everyone (rw-r—r—) but the key can only be read by the owner (rw———-).

I want to have a group that has read access on the key as well as the cert.

This way multiple containers running processes as different users can have access to the certificate and key if required.
